/*
 * Copyright 2026 Ivan Kulenko / Zodiac13
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://apache.org
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

include "common.fbs";

namespace z13.fbs.actions;

enum Action : int16 (action, action_group: "Control") {
  MOVE_FORWARD (display_text: "Move forward", default_keycodes: "KEY_W"),
  MOVE_BACKWARD (display_text: "Move backward", default_keycodes: "KEY_S"),
  MOVE_LEFT (display_text: "Move left", default_keycodes: "KEY_A"),
  MOVE_RIGHT (display_text: "Move right", default_keycodes: "KEY_D"),
  JUMP (display_text: "Move Jump", default_keycodes: "KEY_SPACE"),
  CROUCH (display_text: "Move Crouch", default_keycodes: "KEY_LCTRL"),
  ACTION_1 (display_text: "Action 1", default_keycodes: "MOUSE_BUTTON_LEFT"),
  VERTICAL_LOOK,
  HORIZONTAL_LOOK,
}

table ActionsTable {
}

root_type ActionsTable;