/*
 * Copyright 2026 Ivan Kulenko / Zodiac13
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://apache.org
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

include "common.fbs";
include "geometry.fbs";

namespace z13.fbs.building;

table Wall {}

union BlockContent {
  Wall
}

table Block {
  transform: z13.fbs.geometry.Transform;
  content: BlockContent;
}

enum Action : int16 (action, action_group: "Building") {
  TOGGLE_BUILDING_MODE (display_text: "Toggle building mode", default_keycodes: "KEY_TAB", action_group: "Control"),
  BUILD_BLOCK (display_text: "Test block build", default_keycodes: "MOUSE_BUTTON_LEFT"),
  DESTROY_BLOK (display_text: "Test bFlock destroy", default_keycodes: "MOUSE_BUTTON_RIGHT"),
}

root_type Block;