namespace z13.fbs.input;

attribute "display_text";

enum Keycode : int16 {
  KEY_UNKNOWN = 0 (display_text: "Unknown"),
  KEY_RETURN (display_text: "Enter"),
  KEY_ESCAPE (display_text: "Escape"),
  KEY_BACKSPACE (display_text: "Backspace"),
  KEY_TAB (display_text: "Tab"),
  KEY_SPACE (display_text: "Space"),
  KEY_EXCLAIM (display_text: "!"),
  KEY_QUOTEDBL (display_text: "\""),
  KEY_HASH (display_text: "#"),
  KEY_PERCENT (display_text: "%"),
  KEY_DOLLAR (display_text: "$"),
  KEY_AMPERSAND (display_text: "&"),
  KEY_QUOTE (display_text: "'"),
  KEY_LEFTPAREN (display_text: "("),
  KEY_RIGHTPAREN (display_text: ")"),
  KEY_ASTERISK (display_text: "*"),
  KEY_PLUS (display_text: "+"),
  KEY_COMMA (display_text: ","),
  KEY_MINUS (display_text: "-"),
  KEY_PERIOD (display_text: "."),
  KEY_SLASH (display_text: "/"),
  KEY_0 (display_text: "0"),
  KEY_1 (display_text: "1"),
  KEY_2 (display_text: "2"),
  KEY_3 (display_text: "3"),
  KEY_4 (display_text: "4"),
  KEY_5 (display_text: "5"),
  KEY_6 (display_text: "6"),
  KEY_7 (display_text: "7"),
  KEY_8 (display_text: "8"),
  KEY_9 (display_text: "9"),
  KEY_COLON (display_text: ":"),
  KEY_SEMICOLON (display_text: ";"),
  KEY_LESS (display_text: "<"),
  KEY_EQUALS (display_text: "="),
  KEY_GREATER (display_text: ">"),
  KEY_QUESTION (display_text: "?"),
  KEY_AT (display_text: "@"),
  KEY_LEFTBRACKET (display_text: "["),
  KEY_BACKSLASH (display_text: "\\"),
  KEY_RIGHTBRACKET (display_text: "]"),
  KEY_CARET (display_text: "^"),
  KEY_UNDERSCORE (display_text: "_"),
  KEY_BACKQUOTE (display_text: "`"),
  KEY_A (display_text: "A"),
  KEY_B (display_text: "B"),
  KEY_C (display_text: "C"),
  KEY_D (display_text: "D"),
  KEY_E (display_text: "E"),
  KEY_F (display_text: "F"),
  KEY_G (display_text: "G"),
  KEY_H (display_text: "H"),
  KEY_I (display_text: "I"),
  KEY_J (display_text: "J"),
  KEY_K (display_text: "K"),
  KEY_L (display_text: "L"),
  KEY_M (display_text: "M"),
  KEY_N (display_text: "N"),
  KEY_O (display_text: "O"),
  KEY_P (display_text: "P"),
  KEY_Q (display_text: "Q"),
  KEY_R (display_text: "R"),
  KEY_S (display_text: "S"),
  KEY_T (display_text: "T"),
  KEY_U (display_text: "U"),
  KEY_V (display_text: "V"),
  KEY_W (display_text: "W"),
  KEY_X (display_text: "X"),
  KEY_Y (display_text: "Y"),
  KEY_Z (display_text: "Z"),
  KEY_CAPSLOCK (display_text: "Capslock"),
  KEY_F1 (display_text: "F1"),
  KEY_F2 (display_text: "F2"),
  KEY_F3 (display_text: "F3"),
  KEY_F4 (display_text: "F4"),
  KEY_F5 (display_text: "F5"),
  KEY_F6 (display_text: "F6"),
  KEY_F7 (display_text: "F7"),
  KEY_F8 (display_text: "F8"),
  KEY_F9 (display_text: "F9"),
  KEY_F10 (display_text: "F10"),
  KEY_F11 (display_text: "F11"),
  KEY_F12 (display_text: "F12"),
  KEY_PRINTSCREEN (display_text: "PrtScr"),
  KEY_SCROLLLOCK (display_text: "ScrollLock"),
  KEY_PAUSE (display_text: "Pause"),
  KEY_INSERT (display_text: "Insert"),
  KEY_HOME (display_text: "Home"),
  KEY_PAGEUP (display_text: "PageUp"),
  KEY_DELETE (display_text: "Delete"),
  KEY_END (display_text: "End"),
  KEY_PAGEDOWN (display_text: "PageDown"),
  KEY_RIGHT (display_text: "Right"),
  KEY_LEFT (display_text: "Left"),
  KEY_DOWN (display_text: "Down"),
  KEY_UP (display_text: "Up"),
  KEY_NUMLOCKCLEAR (display_text: "NumLock"),
  KEY_KP_DIVIDE (display_text: "KP_Divide"),
  KEY_KP_MULTIPLY (display_text: "KP_Multiply"),
  KEY_KP_MINUS (display_text: "KP_Minus"),
  KEY_KP_PLUS (display_text: "KP_Plus"),
  KEY_KP_ENTER (display_text: "KP_Enter"),
  KEY_KP_1 (display_text: "KP_1"),
  KEY_KP_2 (display_text: "KP_2"),
  KEY_KP_3 (display_text: "KP_3"),
  KEY_KP_4 (display_text: "KP_4"),
  KEY_KP_5 (display_text: "KP_5"),
  KEY_KP_6 (display_text: "KP_6"),
  KEY_KP_7 (display_text: "KP_7"),
  KEY_KP_8 (display_text: "KP_8"),
  KEY_KP_9 (display_text: "KP_9"),
  KEY_KP_0 (display_text: "KP_0"),
  KEY_KP_PERIOD (display_text: "Enter"),
  KEY_LCTRL (display_text: "LCtrl"),
  KEY_LSHIFT(display_text: "LShift"),
  KEY_LALT (display_text: "LAlt"),
  KEY_LGUI (display_text: "LGui"),
  KEY_RCTRL (display_text: "RCtrl"),
  KEY_RSHIFT(display_text: "RShift"),
  KEY_RALT (display_text: "RAlt"),
  KEY_RGUI (display_text: "RGui"),
  MOUSE_BUTTON_LEFT (display_text: "MLeft"),
  MOUSE_BUTTON_MIDDLE (display_text: "MMiddle"),
  MOUSE_BUTTON_RIGHT (display_text: "MRight"),
  MOUSE_BUTTON_X1 (display_text: "MX1"),
  MOUSE_BUTTON_X2 (display_text: "MX2"),
  MOUSE_BUTTON_UNKNOWN (display_text: "MUnknown"),
}

enum Action : int16 {
  MOVE_FORWARD (display_text: "Move forward"),
  MOVE_BACKWARD (display_text: "Move backward"),
  MOVE_LEFT (display_text: "Move left"),
  MOVE_RIGHT (display_text: "Move right"),
  JUMP (display_text: "Move Jump"),
  CROUCH (display_text: "Move Crouch"),
  VERTICAL_LOOK,
  HORIZONTAL_LOOK,
}

table ActionBinding {
  action: Action;
  key_codes: [Keycode]; 
}

table MouseConfig {
  mouse_sensitivity: float;
  invert_x: bool;
  invert_y: bool;
}

table InputConfig {
  action_bindings: [ActionBinding];
  mouse_config: MouseConfig;
}

root_type InputConfig;