syntax = "proto3";

package z13.proto.input;

import "google/protobuf/descriptor.proto";

message EnumValueDetails {
  string display_text = 1;
}

extend google.protobuf.EnumValueOptions {
  EnumValueDetails details = 1000;
}

message Keyboard {
  enum Code {
    KEY_UNKNOWN = 0 [(details).display_text = "Unknown"];
    KEY_RETURN = 1 [(details).display_text = "Enter"];
    KEY_ESCAPE = 2 [(details).display_text = "Escape"];
    KEY_BACKSPACE = 3 [(details).display_text = "Backspace"];
    KEY_TAB = 4 [(details).display_text = "Tab"];
    KEY_SPACE = 5 [(details).display_text = "Space"];
    KEY_EXCLAIM = 6 [(details).display_text = "!"];
    KEY_QUOTEDBL = 7 [(details).display_text = "\""];
    KEY_HASH = 8 [(details).display_text = "#"];
    KEY_PERCENT = 9 [(details).display_text = "%"];
    KEY_DOLLAR = 10 [(details).display_text = "$"];
    KEY_AMPERSAND = 11 [(details).display_text = "&"];
    KEY_QUOTE = 12 [(details).display_text = "'"];
    KEY_LEFTPAREN = 13 [(details).display_text = "("];
    KEY_RIGHTPAREN = 14 [(details).display_text = ")"];
    KEY_ASTERISK = 15 [(details).display_text = "*"];
    KEY_PLUS = 16 [(details).display_text = "+"];
    KEY_COMMA = 17 [(details).display_text = ","];
    KEY_MINUS = 18 [(details).display_text = "-"];
    KEY_PERIOD = 19 [(details).display_text = "."];
    KEY_SLASH = 20 [(details).display_text = "/"];
    KEY_0 = 21 [(details).display_text = "0"];
    KEY_1 = 22 [(details).display_text = "1"];
    KEY_2 = 23 [(details).display_text = "2"];
    KEY_3 = 24 [(details).display_text = "3"];
    KEY_4 = 25 [(details).display_text = "4"];
    KEY_5 = 26 [(details).display_text = "5"];
    KEY_6 = 27 [(details).display_text = "6"];
    KEY_7 = 28 [(details).display_text = "7"];
    KEY_8 = 29 [(details).display_text = "8"];
    KEY_9 = 30 [(details).display_text = "9"];
    KEY_COLON = 31 [(details).display_text = ":"];
    KEY_SEMICOLON = 32 [(details).display_text = ";"];
    KEY_LESS = 33 [(details).display_text = "<"];
    KEY_EQUALS = 34 [(details).display_text = "="];
    KEY_GREATER = 35 [(details).display_text = ">"];
    KEY_QUESTION = 36 [(details).display_text = "?"];
    KEY_AT = 37 [(details).display_text = "@"];
    KEY_LEFTBRACKET = 38 [(details).display_text = "["];
    KEY_BACKSLASH = 39 [(details).display_text = "\\"];
    KEY_RIGHTBRACKET = 40 [(details).display_text = "]"];
    KEY_CARET = 41 [(details).display_text = "^"];
    KEY_UNDERSCORE = 42 [(details).display_text = "_"];
    KEY_BACKQUOTE = 43 [(details).display_text = "`"];
    KEY_A = 44 [(details).display_text = "A"];
    KEY_B = 45 [(details).display_text = "B"];
    KEY_C = 46 [(details).display_text = "C"];
    KEY_D = 47 [(details).display_text = "D"];
    KEY_E = 48 [(details).display_text = "E"];
    KEY_F = 49 [(details).display_text = "F"];
    KEY_G = 50 [(details).display_text = "G"];
    KEY_H = 51 [(details).display_text = "H"];
    KEY_I = 52 [(details).display_text = "I"];
    KEY_J = 53 [(details).display_text = "J"];
    KEY_K = 54 [(details).display_text = "K"];
    KEY_L = 55 [(details).display_text = "L"];
    KEY_M = 56 [(details).display_text = "M"];
    KEY_N = 57 [(details).display_text = "N"];
    KEY_O = 58 [(details).display_text = "O"];
    KEY_P = 59 [(details).display_text = "P"];
    KEY_Q = 60 [(details).display_text = "Q"];
    KEY_R = 61 [(details).display_text = "R"];
    KEY_S = 62 [(details).display_text = "S"];
    KEY_T = 63 [(details).display_text = "T"];
    KEY_U = 64 [(details).display_text = "U"];
    KEY_V = 65 [(details).display_text = "V"];
    KEY_W = 66 [(details).display_text = "W"];
    KEY_X = 67 [(details).display_text = "X"];
    KEY_Y = 68 [(details).display_text = "Y"];
    KEY_Z = 69 [(details).display_text = "Z"];
    KEY_CAPSLOCK = 70 [(details).display_text = "Capslock"];
    KEY_F1 = 71 [(details).display_text = "F1"];
    KEY_F2 = 72 [(details).display_text = "F2"];
    KEY_F3 = 73 [(details).display_text = "F3"];
    KEY_F4 = 74 [(details).display_text = "F4"];
    KEY_F5 = 75 [(details).display_text = "F5"];
    KEY_F6 = 76 [(details).display_text = "F6"];
    KEY_F7 = 77 [(details).display_text = "F7"];
    KEY_F8 = 78 [(details).display_text = "F8"];
    KEY_F9 = 79 [(details).display_text = "F9"];
    KEY_F10 = 80 [(details).display_text = "F10"];
    KEY_F11 = 81 [(details).display_text = "F11"];
    KEY_F12 = 82 [(details).display_text = "F12"];
    KEY_PRINTSCREEN = 83 [(details).display_text = "PrtScr"];
    KEY_SCROLLLOCK = 84 [(details).display_text = "ScrollLock"];
    KEY_PAUSE = 85 [(details).display_text = "Pause"];
    KEY_INSERT = 86 [(details).display_text = "Insert"];
    KEY_HOME = 87 [(details).display_text = "Home"];
    KEY_PAGEUP = 88 [(details).display_text = "PageUp"];
    KEY_DELETE = 89 [(details).display_text = "Delete"];
    KEY_END = 90 [(details).display_text = "End"];
    KEY_PAGEDOWN = 91 [(details).display_text = "PageDown"];
    KEY_RIGHT = 92 [(details).display_text = "Right"];
    KEY_LEFT = 93 [(details).display_text = "Left"];
    KEY_DOWN = 94 [(details).display_text = "Down"];
    KEY_UP = 95 [(details).display_text = "Up"];
    KEY_NUMLOCKCLEAR = 96 [(details).display_text = "NumLock"];
    KEY_KP_DIVIDE = 97 [(details).display_text = "KP_Divide"];
    KEY_KP_MULTIPLY = 98 [(details).display_text = "KP_Multiply"];
    KEY_KP_MINUS = 99 [(details).display_text = "KP_Minus"];
    KEY_KP_PLUS = 100 [(details).display_text = "KP_Plus"];
    KEY_KP_ENTER = 101 [(details).display_text = "KP_Enter"];
    KEY_KP_1 = 102 [(details).display_text = "KP_1"];
    KEY_KP_2 = 103 [(details).display_text = "KP_2"];
    KEY_KP_3 = 104 [(details).display_text = "KP_3"];
    KEY_KP_4 = 105 [(details).display_text = "KP_4"];
    KEY_KP_5 = 106 [(details).display_text = "KP_5"];
    KEY_KP_6 = 107 [(details).display_text = "KP_6"];
    KEY_KP_7 = 108 [(details).display_text = "KP_7"];
    KEY_KP_8 = 109 [(details).display_text = "KP_8"];
    KEY_KP_9 = 110 [(details).display_text = "KP_9"];
    KEY_KP_0 = 111 [(details).display_text = "KP_0"];
    KEY_KP_PERIOD = 112 [(details).display_text = "KP_."];
    KEY_LCTRL = 113 [(details).display_text = "LCtrl"];
    KEY_LSHIFT = 114 [(details).display_text = "LShift"];
    KEY_LALT = 115 [(details).display_text = "LAlt"];
    KEY_LGUI = 116 [(details).display_text = "LGui"];
    KEY_RCTRL = 117 [(details).display_text = "RCtrl"];
    KEY_RSHIFT = 118 [(details).display_text = "RShift"];
    KEY_RALT = 119 [(details).display_text = "RAlt"];
    KEY_RGUI = 120 [(details).display_text = "RGui"];
    MOUSE_BUTTON_LEFT = 121 [(details).display_text = "MLeft"];
    MOUSE_BUTTON_MIDDLE = 122 [(details).display_text = "MMiddle"];
    MOUSE_BUTTON_RIGHT = 123 [(details).display_text = "MRight"];
    MOUSE_BUTTON_X1 = 124 [(details).display_text = "MX1"];
    MOUSE_BUTTON_X2 = 125 [(details).display_text = "MX2"];
    MOUSE_BUTTON_UNKNOWN = 126 [(details).display_text = "MUnknown"];
  }
}

message Action {
  enum ActionType {
    MOVE_FORWARD = 0 [(details).display_text = "Move forward"];
    MOVE_BACKWARD = 1 [(details).display_text = "Move backward"];
    MOVE_LEFT = 2 [(details).display_text = "Move left"];
    MOVE_RIGHT = 3 [(details).display_text = "Move right"];
    JUMP = 4 [(details).display_text = "Jump"];
    CROUCH = 5 [(details).display_text = "Crouch"];
    VERTICAL_LOOK = 100;
    HORIZONTAL_LOOK = 101;
  }
}

message ActionBinding {
  Action.ActionType action = 1;
  repeated Keyboard.Code key_codes = 2;  
}

message MouseConfig {
  float mouse_sensitivity = 2;
  bool invert_x = 3;
  bool invert_y = 4;
}

message InputConfig {
  repeated ActionBinding action_bindings = 1;
  MouseConfig mouse_config = 2;
}